CREATE DATABASE caterlordpos;
CREATE USER 'lfpos'@'%' IDENTIFIED BY 'lfpos';
GRANT ALL PRIVILEGES ON `caterlordpos` . * TO 'lfpos'@'%';

USE caterlordpos;

CREATE TABLE `sales_detail` (
  `id` varchar(32) NOT NULL,
  `seqNo` bigint(20) DEFAULT NULL,
  `shopName` varchar(32) DEFAULT NULL,
  `transactionId` varchar(32) DEFAULT NULL,
  `itemCode` varchar(32) DEFAULT NULL,
  `itemName` varchar(63) DEFAULT NULL,
  `category` varchar(32) DEFAULT NULL,
  `department` varchar(32) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `qty` int(11) DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `codeChange` varchar(32) DEFAULT NULL,
  `orderUser` varchar(32) DEFAULT NULL,
  `orderDateTime` datetime DEFAULT NULL,
  `txDate` varchar(15) DEFAULT NULL,
  `shopId` varchar(8) DEFAULT NULL,
  `filename` varchar(63) DEFAULT NULL,
  `isParsed` tinyint(1) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tlps_a` (
  `id` varchar(31) NOT NULL,
  `txId` varchar(31) DEFAULT NULL,
  `txDateTime` datetime DEFAULT NULL,
  `txDate` varchar(10) DEFAULT NULL,
  `txTime` varchar(10) DEFAULT NULL,
  `shopId` varchar(20) DEFAULT NULL,
  `shopName` varchar(63) DEFAULT NULL,
  `itemCode` varchar(31) DEFAULT NULL,
  `itemName` varchar(63) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `qty` int(11) DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `orderUserId` varchar(15) DEFAULT NULL,
  `maleCount` int(11) DEFAULT NULL,
  `femaleCount` int(11) DEFAULT NULL,
  `category` varchar(15) DEFAULT NULL,
  `discountAmount` bigint(20) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `txCategory` varchar(15) DEFAULT NULL,
  `transactionId` varchar(15) DEFAULT NULL,
  `seqNo` int(11) DEFAULT NULL,
  `filename` text,
  `isParsed` tinyint(1) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `tlps_e` (
  `id` varchar(31) NOT NULL,
  `txId` varchar(31) DEFAULT NULL,
  `txDateTime` datetime DEFAULT NULL,
  `txDate` varchar(10) DEFAULT NULL,
  `txTime` varchar(10) DEFAULT NULL,
  `shopId` varchar(20) DEFAULT NULL,
  `shopName` varchar(63) DEFAULT NULL,
  `orderUserId` varchar(20) DEFAULT NULL,
  `transactionId` varchar(20) DEFAULT NULL,
  `seqNo` int(11) DEFAULT NULL,
  `itemCode` varchar(15) DEFAULT NULL,
  `qty` int(11) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `cash` double DEFAULT NULL,
  `creditCard` double DEFAULT NULL,
  `coupon` double DEFAULT NULL,
  `chipCard` double DEFAULT NULL,
  `payWay5` double DEFAULT NULL,
  `payWay6` double DEFAULT NULL,
  `payWay7` double DEFAULT NULL,
  `payWay8` double DEFAULT NULL,
  `payWayCategory` varchar(20) DEFAULT NULL,
  `filename` text,
  `isParsed` tinyint(1) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `tlps_f` (
  `id` varchar(31) NOT NULL,
  `txId` varchar(31) DEFAULT NULL,
  `txDateTime` datetime DEFAULT NULL,
  `txDate` varchar(10) DEFAULT NULL,
  `txTime` varchar(10) DEFAULT NULL,
  `shopId` varchar(20) DEFAULT NULL,
  `shopName` varchar(63) DEFAULT NULL,
  `itemCode` varchar(31) DEFAULT NULL,
  `itemName` varchar(63) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `qty` int(11) DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `orderUserId` varchar(15) DEFAULT NULL,
  `maleCount` int(11) DEFAULT NULL,
  `femaleCount` int(11) DEFAULT NULL,
  `category` varchar(15) DEFAULT NULL,
  `discountAmount` bigint(20) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `txCategory` varchar(15) DEFAULT NULL,
  `UseType` varchar(15) DEFAULT NULL,
  `transactionId` varchar(15) DEFAULT NULL,
  `seqNo` int(11) DEFAULT NULL,
  `filename` text,
  `isParsed` tinyint(1) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `tlps_h` (
  `id` varchar(31) NOT NULL,
  `txId` varchar(31) DEFAULT NULL,
  `txDateTime` datetime DEFAULT NULL,
  `txDate` varchar(10) DEFAULT NULL,
  `txTime` varchar(10) DEFAULT NULL,
  `shopId` varchar(20) DEFAULT NULL,
  `shopName` varchar(63) DEFAULT NULL,
  `itemCode` varchar(31) DEFAULT NULL,
  `itemName` varchar(63) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `qty` int(11) DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `orderUserId` varchar(15) DEFAULT NULL,
  `maleCount` int(11) DEFAULT NULL,
  `femaleCount` int(11) DEFAULT NULL,
  `category` varchar(15) DEFAULT NULL,
  `discountAmount` bigint(20) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `txCategory` varchar(15) DEFAULT NULL,
  `transactionId` varchar(15) DEFAULT NULL,
  `seqNo` int(11) DEFAULT NULL,
  `filename` text,
  `isParsed` tinyint(1) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `tlps_daily_report` (
  `txDate` varchar(10) NOT NULL,
  `shopId` varchar(10) NOT NULL,
  `orders` bigint(20) DEFAULT NULL,
  `cupAmount` double DEFAULT NULL,
  `cups` int(11) DEFAULT NULL,
  `grossAmount` double DEFAULT NULL,
  `netAmount` double DEFAULT NULL,
  `noDiscountAmt` double DEFAULT NULL,
  `noDiscountNetAmt` double DEFAULT NULL,
  `discount5cups` double DEFAULT NULL,
  `discount5Amount` double DEFAULT NULL,
  `couponCups` int(11) DEFAULT NULL,
  `couponAmount` double DEFAULT NULL,
  `friendCups` int(11) DEFAULT NULL,
  `friendAmount` double DEFAULT NULL,
  `allOrderDiscount` double DEFAULT NULL,
  `conflictDiscount` double DEFAULT NULL,
  `takeoutCups` int(11) DEFAULT NULL,
  `takeoutAmount` double DEFAULT NULL,
  `deliveryCups` int(11) DEFAULT NULL,
  `deliveryAmount` double DEFAULT NULL,
  `ubCups` int(11) DEFAULT NULL,
  `fpCups` int(11) DEFAULT NULL,
  PRIMARY KEY (`txDate`,`shopId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;