"""
Django settings for apiadmin project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(BASE_DIR)
env_file = f'{BASE_DIR}/settings/env_dev.json'

if not os.path.isfile(env_file):
    env_file = f'{BASE_DIR}/settings/env_prod.json'

with open(env_file) as env:
    ENV = json.load(env)
FILES4PARSE = ENV["FILES4PARSE"]
UG_TEMPLATE = ENV["UG_TEMPLATE"]
EXCEL_OUTPUT = ENV["EXCEL_OUTPUT"]

SFTP_ROOT= ENV["SFTP"]['LOCAL_DIR']
SFTP_REMOTE_HOST= ENV["SFTP"]['SFTP_REMOTE_HOST']
SFTP_REMOTE_PORT= ENV["SFTP"]['SFTP_REMOTE_PORT']
SFTP_REMOTE_ACCT= ENV["SFTP"]['SFTP_REMOTE_ACCT']
SFTP_REMOTE_PWD= ENV["SFTP"]['SFTP_REMOTE_PWD']
SFTP_REMOTE_DIR= ENV["SFTP"]['SFTP_REMOTE_DIR']

DATABASES = {
    'sharetea_mysql': {
        'NAME': ENV["DATABASE"]['NAME'],
        'USER': ENV["DATABASE"]['USER'],
        'PASSWORD': ENV["DATABASE"]['PASSWORD'],
        # Or an IP Address that your DB is hosted on
        'HOST': ENV["DATABASE"]['HOST'],
        'PORT': ENV["DATABASE"]['PORT'],
        'DBNAME': ENV["DATABASE"]['DBNAME'],
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'


EMAIL_HOST = ENV["EMAIL"]["HOST"]
EMAIL_PORT = ENV["EMAIL"]["PORT"]
EMAIL_HOST_USER = ENV["EMAIL"]["USER"]
EMAIL_HOST_PASSWORD = ENV["EMAIL"]["PASSWORD"]
EMAIL_USE_SSL = True
EMAIL_RECIPIENT = "thorshu@gmail.com"

GMAIL_HOST = ENV["GMAIL"]["HOST"]
GMAIL_USER = ENV["GMAIL"]["USER"]
GMAIL_PASSWORD = ENV["GMAIL"]["PASSWORD"]

# survey properties
SURVEY_HOST = ENV["SURVEY"]["HOST"]
SURVEY_HOST_USER = ENV["SURVEY"]["USER"]
SURVEY_HOST_PASSWORD = ENV["SURVEY"]["PASSWORD"]
SURVEY_URL = ENV["SURVEY"]["SURVEY_URL"]
NEW_SURVEY_URL = ENV["SURVEY"]["NEW_SURVEY_URL"]
ORACLE_CLIENT = ENV["ORACLE-CLIENT"]
GATEWAY_API_HOST = ENV["GATEWAY_API_HOST"]


